[line_break]
disabled = false

[username]
style_user = "#a6da95 bold"
style_root = "#a6da95 bold"
format = "{ğŸ”»} / [$user]($style) | [$hostname]($style)"
disabled = false
show_always = true

[package]
disabled = true
symbol = "| ğŸ“¦ "

[hostname]
ssh_only = false
format =  "[$hostname](bold red) "
trim_at = ".fritz.box"
disabled = false

[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ—](bold red) "

[cmd_duration]
min_time = 60_000
format = "took [$duration](bold yellow) "

[directory]
truncation_length = 5
truncate_to_repo = true
style = "#c6a0f6"
format = "| ğŸ“‚ [$path](#c6a0f6) "

[git_branch]
symbol = "| ğŸŒ± "  # Ğ¡Ğ¸Ğ¼Ğ±Ğ¾Ğ» | Ñƒ ÑÑ‚Ğ°Ğ½Ğ´Ğ°Ñ€Ğ´Ğ½Ğ¾Ñ˜ Ğ±Ğ¾Ñ˜Ğ¸
truncation_length = 4
truncation_symbol = ""
style = "bold #f5a97f"


[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged = '[++\($count\)](green)'
renamed = "ğŸ’­"
deleted = "ğŸ—‘"

[docker_context]
format = "| [ğŸ‹ $context](blue bold) "

[nodejs]
disabled = true
format = "| [ğŸ¤– $version](bold green) "

[python]
format = "| [ğŸ ($version)](bold green) "

[ruby]
format = "| [ğŸ’ $version](bold red) "

[php]
format = "| [ğŸ˜ $version](bold blue) "

[java]
format = "| [â˜• $version](bold orange) "

[elixir]
format = "| [ğŸŒŸ $version](bold purple) "

[rust]
format = "| [ğŸ¦€ $version](bold red) "

[c]
format = "| [ğŸ› ï¸ $version](bold blue) "

